#!/bin/bash
##
# Terminator: backup and maintenance system for servers
# Copyright 2016 Tim Kennell Jr.
# Licensed under the MIT License (http://opensource.org/licenses/MIT)
##

##########################
# Array ref and function #
##########################
# This script uses bash references (local -n | declare -n) to simplify passing arrays
# Unfortunately, bash uses dynamic variable scopes, making circular refs easy to create
# To avoid this problem, the following convention in funcs has been created:
#   local array_name=$1 # the NAME of the reference
#   local -n _array=$array_name # the REFERENCE itself
#
# array_name:  can easily be passed to other internal functions without creating 
#   a circular reference
# 
# _array:  can be used locally inside the function to access the ref contents

# Prevents PIPESTATUS from hiding errors of future commands in piped commands
set -o pipefail

# Since this is a restore, I am going to assume that the curent working 
#   directory is good enough for an install location
install_location=$(pwd)

# Create log directory if not exists
if ! [[ -d "$install_location/log" ]] ; then
	mkdir "$install_location/log"
fi

# Set up log file
log_file="$install_location/log/restore-attempt.$(date +"%F_%T").log"
touch "$log_file"

# Force all output (echo) through the log file
exec > >(tee -a "$log_file") 2>&1

# Check for terminator.conf file
if ! [[ -f "$install_location/terminator.conf" ]] ; then
	echo "# System check" >> "$log_file"
	echo "E: could not find 'terminator.conf'.  Please run 'setup'" >> \
		"$log_file"

	exit 1
fi

# Load in user configurations
. "$install_location/terminator.conf"

# Default list of directories to exclude from system restoration
# Note the removal of working directory, which is assumed to be the installation location
default_restoration_exclusion_list=(
    "etc/fstab"
    "etc/hostname"
    "etc/hosts"
    "etc/netplan/"
    "etc/default/grub"
    "${PWD#/}"
)

# Prints a message to the user with tty so that it is not logged
user_message() {
    printf '%s\n' "$@" > /dev/tty
}

# Checks if an element is an array
# param ArrayRef $1 -- array to check for a value
# param Any $2 -- value to verify if in provided array
# returns Bool
array_contains() {
    local array_name=$1
    local -n _array=$array_name
    local search_value=$2

    for value in "${_array[@]}" ; do
        if [[ "$search_value" == "$value" ]] ; then
            return 0
        fi
    done

    return 1
}

# Checks string for comma-separated list without spaces
# param ArrayRef $1 -- user-enetered string of comma-separated numbers
# returns Bool
validate_numerical_list() {
    local string="$1"

    # validate comma-separated list without spaces
    if [[ $string =~ ^[0-9]*(,[0-9])*$ ]] ; then
        return 0
    else
        return 1
    fi
}

# Creates an ssh connection that can take a command to pass to the remote host
#   No params, this function wraps the global parameters in the terminator.conf file
local_remote_ssh() {
    ssh -q -F /dev/null \
        -p "$on_site_host_port" \
        -i "$on_site_host_ssh_key" \
        -o IdentitiesOnly=yes \
        -o StrictHostKeyChecking=no \
        -o ConnectTimeout=10 \
        "$on_site_host_user@$on_site_host_domain" \
        "$@"
}

# Checks really quickly for adequate host login possibility
host_login_ok() {
    # ":" is a null operator in bash
    if ! local_remote_ssh ":" ; then
        echo -n "Remote Backup Error:  host ($on_site_host_domain) unable to reached; "
        echo "check host login parameters, firewall settings, and remote server"
        return 1
    fi
    return 0
}

# Acquires an array of backup levels that exist in the systemdump files
#   on a remote host
# param String $1 - backup location
# return ArrayRef $2 - list of backup levels
list_backup_levels() {
    local backup_location=$1
    local -n _return=$2
    local backup_level=""

    while IFS= read -r file ; do
        backup_level=${file#*level_}
        backup_level=${backup_level%%.*}
        backup_list_full_list+=("${backup_level}")
    done < <(
        local_remote_ssh ls -1 "$backup_location"
    )

    # mapfile turns the list of items with line-break delimiters back into an array
    # remember that <(...) processes the output of a command into a std file output
    # mapfile requires a file input
    mapfile -t _return < <(
        printf "%s\n" "${backup_list_full_list[@]}" | sort -nu
    )
}

# Acquire user list of dirs to exclude
# param ArrayRef $1 -- array of suggested exclusion locations
# return ArrayRef $2 -- array of locations to exclude on system restoration
acquire_user_exclusion_dirs() {
    local location_list_name=$1
    local -n _location_list=$location_list_name
    local -n _return=$2

    local input_string='invalid string'
    local exclusion_array=()

    user_message "List of locations to exclude on restore"

    # Iterate through location list and list them numerically
    for (( i = 0; i < ${#_location_list[@]}; i++ )) ; do
        user_message "$((i + 1)). /${_location_list[$i]}"

    done

    user_message \
        "" \
        "Please list the numbers of the directories to remove from this list"

    # Acquire list of locations to remove from restoration exclusion list from user
    while ! validate_numerical_list "$input_string" ; do
        read -rp "Selection: " input_string < /dev/tty 2> /dev/tty # outputs read to tty so that user message is not logged

        if ! validate_numerical_list "$input_string" ; then
            user_message \
                "Invalid input" \
                "Please enter a comma-separated list without spaces"
        fi
    done
    
    # removes user-selected locations from the location exlusion array
    IFS="," read -ra exclusion_array <<< "$input_string"
    for (( i = 0; i < ${#_location_list[@]}; i++ )) ; do
        if ! array_contains exclusion_array "$((i + 1))" ; then
            _return+=("${_location_list[$i]}")
        fi
    done
}

# Creates the string for tar to exclude locations on restore
#   (note:  must be called as follows: 
#               local location_list=();
#               $(create_exclude_string location_list)
#   )
# param ArrayRef $1 -- array of directories to exclude
# return ArrayRef $2 -- array of exclusion strings for restore tar command
create_exclude_array() {
    local location_list_name=$1
    local -n _location_list=$location_list_name
    local exclusion_string_name=$2
    local -n _return=$exclusion_string_name

    for location in "${_location_list[@]}" ; do
        _return+=(--exclude "${location}")
    done
}

# Restores a backup from archive
# param ArrayRef $1 -- array of suggested directories to exclude on restore
# return null
restore() {
    local location_list_name=$1
    local -n _location_list=$location_list_name

    local final_location_list=()
    local exclude_array=()
    local backup_location=$on_site_host_backup_dir"/systemdump/"
    local backup_levels=()
    local remote_backup=""
    local pipeline_status=()
    local ssh_status=0
    local tar_status=0

    # Sanity checks on the server
    if ! host_login_ok ; then
        return 1
    fi

    acquire_user_exclusion_dirs "$location_list_name" final_location_list
    create_exclude_array final_location_list exclude_array

    list_backup_levels "$backup_location" backup_levels
    for backup_level in "${backup_levels[@]}" ; do
        local remote_backup="${backup_location}*.level_${backup_level}.tar.gz*"
        local_remote_ssh cat "$remote_backup" | \
            # tar tzvf - -C / \
            tar xzpvf - -C / \
                --numeric-owner \
                "${exclude_array[@]}"

        pipeline_status=("${PIPESTATUS[@]}")

        ssh_status=${pipeline_status[0]}
        tar_status=${pipeline_status[1]}

        # SSH errors
        if (( ssh_status != 0 )) ; then
            echo "ERROR: SSH failed while restoring backup level $backup_level (status $ssh_status)"
        fi

        # tar errors
        if (( tar_status != 0 )) ; then
            echo "ERROR: tar failed while restoring backup level $backup_level (status $tar_status)"
        fi

        # terminate script if there are any errors
        if (( ssh_status != 0 || tar_status != 0 )) ; then
            return 1
        fi

    done
}

# Views the contents of a file in the backup
#       The idea of this function is to be able to peer into conditionally excluded files
#       for needed configurations
# param String $1 - name of file to check the contents of
# returns Null
view() {
    local backup_file_to_view=$1
    local backup_location=$on_site_host_backup_dir"/systemdump/"
    local final_location_list=()
    local backup_levels=()

    if [[ -z "$backup_file_to_view" ]] ; then
        user_message \
            "Error: no file provided to search"
            return 1
    elif [[ "${backup_file_to_view:0:1}" == "/" ]] ; then
        user_message \
            "Error:  the path should not begin with \"/\""
        return 1
    fi

    list_backup_levels "$backup_location" backup_levels

    for (( i = ${#backup_levels[@]} - 1; i >= 0; i-- )); do
        local backup_level="${backup_levels[$i]}"
        local remote_backup="${backup_location}*.level_${backup_level}.tar.gz*"

        user_message "Checking backup level: $backup_level"
        local_remote_ssh cat "$remote_backup" |
            tar xOzf - --occurrence=1  "$backup_file_to_view" 2> /dev/null
        
        if [[ ${PIPESTATUS[1]} == 0 ]] ; then
            return 0
        fi
    done
    
    user_message "The file ($backup_file_to_view) does not exist in the backup files"
    return 1
}

if [[ "$1" == "view" ]] ; then
    view "$2"
elif [[ -z "$1" ]] ; then
    restore default_restoration _exclusion_list
else
    user_message "Unrecognized parameter"
fi