#!/bin/bash
##
# Terminator: backup and maintenance system for servers
# Copyright 2016 Tim Kennell Jr.
# Licensed under the MIT License (http://opensource.org/licenses/MIT)
##

# Default list of directories to exclude from system restoration
default_restoration_exclusion_list=(
    "etc/fstab"
    "etc/hostname"
    "etc/hosts"
    "etc/netplan/"
    "etc/default/grub"
    "etc/initramfs-tools/"
)

# Checks if an element is an array
# param ArrayRef $1 -- array to check for a value
# param Any $2 -- value to verify if in provided array
# returns Bool
array_contains() {
    local -n _array=$1
    local search_value=$2

    for value in "${_array[@]}" ; do
        if [[ "$search_value" == "$value" ]] ; then
            return 0
        fi
    done

    return 1
}

# 
# list_backup_levels() {

# }

# Checks string for comma-separated list without spaces
# param ArrayRef $1 -- user-enetered string of comma-separated numbers
# returns Bool
validate_numerical_list() {
    local string="$1"

    # validate comma-separated list without spaces
    if [[ $string =~ ^[0-9]+(,[0-9])*$ ]] ; then
        return 0
    else
        return 1
    fi
}

# Acquire user list of dirs to exclude
# param ArrayRef $1 -- array of suggested exclusion locations
# return ArrayRef $2 -- array of locations to exclude on system restoration
acquire_user_exclusion_dirs() {
    local -n _location_list=$1
    local -n _returns=$2

    local input_string='invalid string'
    # local exclusion_array=()

    echo "List of locations to exclude on restore"

    # Iterate through location list and list them numerically
    for (( i = 0; i < ${#_location_list[@]}; i++ )) ; do
        echo $((i + 1)). "/"${_location_list[$i]}

    done

    echo
    echo "Please list the numbers of the directories to remove from this list"

    # Acquire list of locations to remove from restoration exclusion list from user
    while ! validate_numerical_list "$input_string" ; do
        read -rp "Selection: " input_string

        if ! validate_numerical_list "$input_string" ; then
            echo
            echo "Invalid input"
            echo "Please enter a comma-separated list without spaces"
        fi
    done
    
    # removes user-selected locations from the location exlusion array
    IFS="," read -ra exclusion_array <<< "$input_string"
    for (( i = 0; i < ${#_location_list[@]}; i++ )) ; do
        if ! array_contains exclusion_array "$((i + 1))" ; then
            _returns+=("${_location_list[$i]}")
        fi
    done
}


# Creates a finalized list of locations to exclude on system restoration
#   (presumably through user interaction)
#   (note:  must be called as follows: 
#               local final_list=();
#               create_final_location_exclusion_list location_list final_list
#   )
# param ArrayRef $1 -- array of suggested exclusion locations
# return ArrayRef $2 -- externally named return variable to contain returned array
create_final_location_exclusion_list() {
    local -n _location_list=$1
    local -n _returns=$2

}

# Creates the string for tar to exclude locations on restore
#   (note:  must be called as follows: 
#               local location_list=();
#               $(create_exclude_string location_list)
#   )
# param ArrayRef $1 -- array of directories to exclude
# return String
create_exclude_string() {
    local -n _location_list=$1
    local exclusion_string=""

    for location in "${_location_list[@]}" ; do
        exclude_string+="--exclude ${location} "
    done

    echo "${exclude_string}"
}

# Restores a backup from archive
# param 
# return null
restore() {
    tar -xzf backup.tar.gz \
        --exclude='etc/fstab' \
        --exclude='etc/machine-id' \
        --exclude='etc/netplan/*' \
        -C /
}

acquire_user_exclusion_dirs default_restoration_exclusion_list test

echo "${test[@]}"
